server:
   port: 8082

spring:
   profiles:
      active: dev

---

spring:
   profiles: dev
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp
      password: '123456'
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
management:
   endpoints:
      web:
         exposure:
            include: "*"

---

spring:
   profiles: qa
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dcbappqa
      password: '123456'
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true

---

spring:
   profiles: prod
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dcbappprod
      password: '123456'
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
